version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: developerstore-postgres
    environment:
      POSTGRES_DB: DeveloperStore_Dev
      POSTGRES_USER: devstore_user
      POSTGRES_PASSWORD: devstore_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
